contoh = [23,95.4, "2", True]
print(str(contoh))
print("=================================================")
print()
print(f"\t\tBefore\t\t\t")
print()
print("=================================================")
print(f"=\tTipe data sebelum diubah:\t\t=")
print("=================================================")
print(f"=\t{type(contoh[0])}\t\t\t\t=")
print(f"=\t{type(contoh[1])}\t\t\t\t=")
print(f"=\t{type(contoh[2])}\t\t\t\t=")
print(f"=\t{type(contoh[3])}\t\t\t\t=")
total = (contoh[0]) + (contoh[1])
print(f"=\tTotal ({contoh[0]}) + ({contoh[1]}) = {total}\t\t=")
print("=================================================")
print()
print(f"\t\t{"After"}\t\t\t\t")
print()
print("=================================================")
print(f"=\t{"Integer ke Float"}\t\t\t=")
contoh[0] = float(contoh[0])
print(f"=\t{23} menjadi {contoh[0]}\t\t\t\t=")
print("=================================================")
print(f"=\t{"Float ke Integer"}\t\t\t=")
contoh[1] = int(contoh[1])
print(f"=\t{95.4} menjadi {contoh[1]}\t\t\t\t=")
print("=================================================")
print(f"=\t{"String ke Float"}\t\t\t\t=")
contoh[2] = float(contoh[2])
print(f"=\t{2} menjadi {contoh[2]}\t\t\t\t=")
print("=================================================")
print(f"=\t{"Boolean ke Integer"}\t\t\t=")
contoh[3] = int(contoh[3])
print(f"=\t{True} menjadi {contoh[3]}\t\t\t\t=")
print("=================================================")
print(f"=\tTipe data setelah diubah:\t\t=")
print(f"=\t{type(contoh[0])}\t\t\t\t=")
print(f"=\t{type(contoh[1])}\t\t\t\t=")
print(f"=\t{type(contoh[2])}\t\t\t\t=")
print(f"=\t{type(contoh[3])}\t\t\t\t=")
print(f"=\tTotal ({contoh[0]}) + ({contoh[1]}) = {total}\t\t=")
print("=================================================")
contoh = [23.0,95, "2.0", 1]
print(f"=\t{contoh}\t\t\t=")
print("=================================================")

